---
# this playbook contains the main tasks we want to run
- name: download a .tar.gz file
  get_url: url={{ site_tarball }}
           dest={{ file_dest }}
  ignore_errors: yes

- name: check if file now exists
  stat: path={{ file_dest }}
  register: download_file

- name: send alert phone a text if file not created
  local_action: twilio
            account_sid={{ twilio_account_sid }}
            auth_token={{ twilio_auth_token }}
            msg="Failed to download file from {{ site_tarball }}." 
            from_number={{ twilio_number }}
            to_number={{ alert_number }}
  when: not download_file.stat.exists
